service: apollo-lambda-postgraphile

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-express

functions:
  graphql:
    handler: handler.handler
    events:
      - http:
          path: /
          method: POST
          cors: true
    timeout: 10
